openapi: 3.1.0
info:
  title: Lamine Product Bridge
  version: "1.0"
servers:
  - url: https://YOUR_PUBLIC_DOMAIN
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
security:
  - ApiKeyAuth: []
paths:
  /products:
    get:
      operationId: listProducts
      summary: Liste les produits (dossiers sous images_root)
      responses:
        "200": { description: OK }
  /products/{slug}/images:
    get:
      operationId: getProductImages
      summary: URLs publiques des images d’un produit
      parameters:
        - in: path
          name: slug
          required: true
          schema: { type: string }
      responses:
        "200": { description: OK }
        "404": { description: Not found }
  /products/{slug}/descriptions:
    post:
      operationId: saveProductDescription
      summary: Sauvegarde CSV/JSON de la fiche produit
      parameters:
        - in: path
          name: slug
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                short_description: { type: string }
                description: { type: string }
                categories: { type: array, items: { type: string } }
                tags: { type: array, items: { type: string } }
                regular_price: { type: string }
                sale_price: { type: string }
                slug: { type: string }
                focus_keyword: { type: string }
                meta_title: { type: string }
                meta_description: { type: string }
                internal_link: { type: string }
      responses:
        "200": { description: OK }
        "401": { description: Unauthorized }
